# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  install:
    commands:
      - echo "[+] Scanning for security vulnerability within dependencies"
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      # - pipenv check (if pipenv is installed and a Pipfile is in place)
      # - Alternatively: https://www.owasp.org/index.php/OWASP_Dependency_Check
  pre_build:
    commands:
      - echo "[+] Running pre-build tasks"
      - CLOUD_URL="465316005105.dkr.ecr.ap-northeast-1.amazonaws.com/testecr1c3b47fa/ecrtestfunctionbd62314brepo"
      - LASTEST_TAG="ecrtestfunction-d232cddc4649-latest"
      - IMAGE_LASTEST="${CLOUD_URL}:${LASTEST_TAG}"
      - IMAGE_TAG="ecrtestfunction-d232cddc4649-1" #CODEBUILD_SOURCE_VERSION
      - MY_FUNC="ECRTestFunction"
#       - $(aws ecr get-login --no-include-email --region "${AWS_DEFAULT_REGION}") | docker login --username AWS --password-stdin 465316005105.dkr.ecr.ap-northeast-1.amazonaws.com
      - IMAGE_URI=$(aws lambda get-function --function-name $MY_FUNC | jq -r '.Code.ImageUri')
  build:
    commands:
      - echo "[+] Installing dependencies...."
      - docker build --pull -t $IMAGE_LASTEST ./ecr_test
      - echo "Tagging image..."
      - docker tag $IMAGE_LATEST $IMAGE_TAG
      - echo "Pushing image..."
      - docker push $IMAGE_LASTEST
      - docker push $IMAGE_TAG
      - aws lambda update-function-code --function-name $MY_FUNC --image-uri $IMAGE_URI >> /dev/null
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"
# artifacts:
#   files:
#     - packaged.yaml
#   discard-paths: yes

# cache:
#   paths:
#     - '/root/.cache/pip'
