version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mbcsso-dev-ci"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15wy90y4nj0it"
s3_prefix = "mbcsso-dev-ci"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SystemName=\"mbcsso\" Env=\"dev\" SourceCodeProvider=\"GitHub\" GitHubOAuthToken=\"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\" GitHubOwner=\"voccer\" GitHubRepo=\"test_ecr\" GitHubBranch=\"main\" BuildSpecFilePath=\"buildspec.yaml\""
image_repositories = []
